import { useState } from "react";
import { Button, Surface } from "@heroui/react";
import { FileText, FolderOpen, CheckCircle, AlertCircle } from "lucide-react";
import { pdf, Text, View, StyleSheet } from "@react-pdf/renderer";
import { invoke } from "@tauri-apps/api/core";
import { join } from "@tauri-apps/api/path";
import { PdfDocument } from "../reports/PdfDocument";
import type { Group } from "../types/group";

const REPORTS_FOLDER_KEY = "tizara-reports-folder";

const testStyles = StyleSheet.create({
  section: { marginBottom: 16 },
  heading: { fontFamily: "Helvetica-Bold", fontSize: 12, marginBottom: 6, color: "#2d3748" },
  body: { fontSize: 10, color: "#4a5568", lineHeight: 1.5 },
});

function TestContent() {
  return (
    <View style={testStyles.section}>
      <Text style={testStyles.heading}>Pipeline Verification</Text>
      <Text style={testStyles.body}>
        This is a test report generated by Tizara to verify that the PDF pipeline is working correctly.
        Reports will contain student data, attendance records, grades, notes, and more.
      </Text>
    </View>
  );
}

interface ReportsPageProps {
  group: Group;
}

export function ReportsPage({ group }: ReportsPageProps) {
  const [generating, setGenerating] = useState(false);
  const [result, setResult] = useState<{ ok: boolean; message: string } | null>(null);

  const folder = localStorage.getItem(REPORTS_FOLDER_KEY);

  async function handleGenerateTest() {
    if (!folder) {
      setResult({ ok: false, message: "No output folder configured. Go to Settings → Files to set one." });
      return;
    }

    setGenerating(true);
    setResult(null);

    try {
      const doc = (
        <PdfDocument
          title="Test Report"
          groupName={group.name}
          schoolName={group.school_name}
          generatedDate={new Date().toLocaleDateString()}
        >
          <TestContent />
        </PdfDocument>
      );

      const blob = await pdf(doc).toBlob();
      const arrayBuffer = await blob.arrayBuffer();
      const bytes = new Uint8Array(arrayBuffer);

      const base64 = btoa(
        Array.from(bytes)
          .map((b) => String.fromCharCode(b))
          .join("")
      );

      const ts = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
      const filename = `tizara-test-${ts}.pdf`;
      const filePath = await join(folder, filename);

      await invoke("write_pdf", { path: filePath, dataBase64: base64 });
      setResult({ ok: true, message: `Saved to ${filePath}` });
    } catch (err) {
      setResult({ ok: false, message: String(err) });
    } finally {
      setGenerating(false);
    }
  }

  return (
    <div className="p-6 flex flex-col h-full">
      <div className="mb-6">
        <h2 className="text-2xl font-bold flex items-center gap-2">
          <FileText size={22} />
          Reports
        </h2>
        <p className="text-sm text-muted mt-0.5">
          Generate PDF reports for your group or individual students.
        </p>
      </div>

      {!folder && (
        <Surface className="flex items-start gap-3 px-4 py-3 rounded-lg mb-4 border border-warning/30 bg-warning/5">
          <FolderOpen size={16} className="text-warning mt-0.5 shrink-0" />
          <p className="text-sm text-foreground/70">
            No output folder configured. Go to{" "}
            <strong>Settings → Files</strong> to choose where PDFs will be saved.
          </p>
        </Surface>
      )}

      <Surface className="flex items-center justify-between gap-4 px-4 py-3 rounded-lg mb-4">
        <div className="flex flex-col gap-0.5">
          <span className="text-sm font-medium">Pipeline Test</span>
          <span className="text-xs text-foreground/50">
            Generate a minimal PDF to verify the output folder and save pipeline are working.
          </span>
        </div>
        <Button
          variant="secondary"
          size="sm"
          isDisabled={generating}
          onPress={handleGenerateTest}
        >
          {generating ? "Generating…" : "Generate Test PDF"}
        </Button>
      </Surface>

      {result && (
        <Surface className={`flex items-start gap-3 px-4 py-3 rounded-lg ${result.ok ? "border-success/30 bg-success/5" : "border-danger/30 bg-danger/5"}`}>
          {result.ok
            ? <CheckCircle size={16} className="text-success mt-0.5 shrink-0" />
            : <AlertCircle size={16} className="text-danger mt-0.5 shrink-0" />
          }
          <p className="text-sm break-all">{result.message}</p>
        </Surface>
      )}

      <div className="mt-8 text-center text-foreground/30 text-sm">
        Report modules are coming in the next stages.
      </div>
    </div>
  );
}
